name: R Package Release

on:
  push:
    tags:
      - 'v*'  # 当推送以v开头的标签时触发，例如v2.1.1

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      
      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::devtools
            any::roxygen2
      
      - name: Install BioConductor dependencies
        run: |
          if (!requireNamespace("BiocManager", quietly = TRUE))
            install.packages("BiocManager")
          BiocManager::install(c("KEGGREST", "ComplexHeatmap", "Biobase", "BiocGenerics", "DESeq2", "edgeR", "limma", "SummarizedExperiment"))
        shell: Rscript {0}
      
      - name: Document
        run: |
          roxygen2::roxygenize()
        shell: Rscript {0}
      
      - name: Build source package
        run: |
          pkg_file <- devtools::build(binary = FALSE)
          # 将文件路径保存到环境变量中，以便后续步骤使用
          cat(sprintf("PKG_FILE=%s\n", pkg_file), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
          cat(sprintf("PKG_NAME=%s\n", basename(pkg_file)), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        shell: Rscript {0}
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ggpicrust2 ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: ${{ env.PKG_FILE }}
          body: |
            # ggpicrust2 ${{ env.VERSION }}
            
            This release contains the source package for ggpicrust2 version ${{ env.VERSION }}.
            
            ## Installation
            
            You can install this release directly from GitHub:
            
            ```r
            # Install from GitHub release
            install.packages("${{ env.PKG_NAME }}", repos = NULL, type = "source")
            
            # Or using devtools
            devtools::install_github("cafferychen777/ggpicrust2@v${{ env.VERSION }}")
            ```
            
            See the [NEWS.md](https://github.com/cafferychen777/ggpicrust2/blob/main/NEWS.md) file for details on changes in this version.